### ISSUE TITLE
add  append_global_option(k,v) and postpone ao_initialize()

### ISSUE THREAD

**Issue by peterbillam** [TheLinx/lao#7]
To allow setting quiet=yes in time to stop the debug messages emitted by ao_initialize(),
I suggest  we add a append_global_option(k,v) function, and delay calling ao_initialize() until the next function is called.

If that function is append_global_option then we call that first and ao_initialize second (assuming it works that way round), whereas if it's some other function like open() then we call ao_initialize first and the function second.

**Comment by daurnimator** [comment]
See PR #6
